apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: upbound-aws-providerconfigs-rwx
  labels:
    rbac.crossplane.io/aggregate-to-provider: "true"
rules:
  - apiGroups: ["aws.upbound.io"]
    resources:
      - providerconfigs
      - providerconfigs/status
      - providerconfigusages
      - providerconfigusages/status
    verbs: ["get","list","watch","create","update","patch"]
  - apiGroups: [""]
    resources:
      - secrets
    verbs: ["get","list","watch"]
