kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # map host:80 → KIND node:30080 (NGINX http)
      - containerPort: 30080
        hostPort: 80
        protocol: TCP
      # map host:443 → KIND node:30443 (NGINX https)
      - containerPort: 30443
        hostPort: 443
        protocol: TCP
