apiVersion: pkg.crossplane.io/v1
kind: ControllerConfig
metadata:
  name: localstack-cc
spec:
  # Optional: see controller logs with more detail
  args:
    - --debug
  env:
    # Make the controllers talk to LocalStack (inside the cluster)
    - name: AWS_REGION
      value: us-east-1
    - name: AWS_ENDPOINT_URL
      value: http://localstack.localstack.svc.cluster.local:4566
    - name: AWS_S3_USE_PATH_STYLE
      value: "true"
