apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - controllerconfig-localstack.yaml
  - provider-aws-s3.yaml
  - provider-aws-sqs.yaml
# NOTE:
# Do NOT include a provider-family YAML here, or it will clash with the individual providers.
